name: Gradle Publish to Maven Central

on:
  push:
    tags:
      - '.+-rv\d+'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Publish to Sonatype
        env:
          TAG_VERSION: ${{ github.ref_name }}
        run: |
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -Peula=true
          echo "Version: ${TAG_VERSION}" >> $GITHUB_STEP_SUMMARY
